# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
