plugins: [jekyll-paginate-v2]

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  limit: 0
  sort_reverse: true
  trail:
    before: 2
    after: 2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
